
export const CATAGORY1_LOADING = 'CATAGORY1_LOADING';
export const CATAGORY1_FAILED = 'CATAGORY1_FAILED';
export const ADD_CATAGORY1 = 'ADD_CATAGORY1';


export const CATAGORY2_LOADING = 'CATAGORY2_LOADING';
export const CATAGORY2_FAILED = 'CATAGORY2_FAILED';
export const ADD_CATAGORY2 = 'ADD_CATAGORY2';